lang: python
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: always
sudo: required
services:
- docker
before_install:
- docker pull fedora:23
install:
- sudo pip install coveralls
before_script:
- docker run -i --privileged -d -v $HOME/build/$TRAVIS_REPO_SLUG:$HOME/build/$TRAVIS_REPO_SLUG --name test_fedora fedora:23 bash
- docker exec -i test_fedora bash -c "dnf install -y python-copr mock tito libsolv-devel make gcc gcc-c++ python3-dnf python-devel 'dnf-command(builddep)'; dnf builddep -y $HOME/build/$TRAVIS_REPO_SLUG/rpg.spec"
- docker exec -i test_fedora bash -c "dnf builddep -y hawkey"
- docker exec -i test_fedora bash -c "dnf builddep -y libhif"
- docker exec -i test_fedora bash -c "dnf builddep -y libsolv"
- docker exec -i test_fedora bash -c "dnf install -y python-pip python3-nose-cov git which; pip install coveralls flake8 flake8-diff"
- docker exec -i test_fedora bash -c "useradd -g root fedora; usermod -a -G mock fedora"
script:
- rel-eng/travis/build.sh
